# Generated by Django 6.0.4 on 2026-04-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='account_name',
            field=models.CharField(default='Church Account', max_length=200),
        ),
    ]
