# Generated by Django 6.0.4 on 2026-04-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_accountdetail_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='accent_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='secondary_color',
            field=models.CharField(default='#4f46e5', max_length=20),
        ),
    ]
