# Generated by Django 6.0.4 on 2026-04-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_service_accent_color_service_secondary_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='service',
            name='secondary_color',
        ),
    ]
