# Generated by Django 6.0.4 on 2026-04-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_remove_service_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Full URL to Facebook page', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Full URL to Instagram profile', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Full URL to Twitter/X profile', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Full URL to YouTube channel', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='theme_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
    ]
