# Generated by Django 6.0.4 on 2026-04-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_service_facebook_url_service_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='facebook_url',
        ),
        migrations.AddField(
            model_name='service',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='Full URL to TikTok profile', max_length=500, null=True),
        ),
    ]
