# Generated by Django 4.1.13 on 2026-04-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_remove_service_facebook_url_service_tiktok_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
