# Generated by Django 4.1.13 on 2026-04-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_usersubmission_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='Full URL to WhatsApp group or contact', max_length=500, null=True),
        ),
    ]
